#!/usr/bin/env python

'''
    This module creates the motion commands list
'''

import numpy as np
import math

def create_motion_commands():
    
    robot_vel = []

    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0, math.pi/4],
                [0, math.pi/4],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0, -math.pi/4],
                [0.05, 0],
                [0.05, 0],
                [0, -math.pi/4]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))


    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0.05, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0.05, 0],
                [0, -math.pi/4],
                [0.05, 0]]))
    
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))

    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, -math.pi/4],
                [0, -math.pi/4],
                [0.05, 0]]))

    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, math.pi/4],
                [0, 0],
                [0.05, 0]]))
    
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))
    robot_vel.append(np.array([[0.05, 0],
                [0, 0],
                [0, 0],
                [0.05, 0]]))

    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    robot_vel.append(np.array([[0, math.pi/4],
                [0, 0],
                [0, 0],
                [0, math.pi/4]]))
    return robot_vel, len(robot_vel)